version: '3'

services:
  grafana:
    image: angizeh-grafana2:latest   # Use the custom image
    container_name: ang-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    restart: always

volumes:
  grafana_data:
